C4Container
    title Container Diagram for e-scooter and e-bike rental

    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")
    Enterprise_Boundary(b1, "MobiCorp Rental System") {
        Person(user, "User", "A MobiCorp user")

        Container_Boundary(c1, "Customer Facing Subsystem") {
            Container(mobile, "Mobile App", "iOS/Android", "Provides rental functionality")
            Container(webserver, "Web Server", "API Gateway", "Handles API requests from mobile app, authenticates user")
        }

        Container_Boundary(c2, "Core Services") {
            Container(paymentService, "Payment Service", "Service", "Charges users, validates payment methods")
            Container(bookingService, "Booking Service", "Service", "Keeps track of booked vehicles")
            Container(locationService, "Location Service", "Service", "Keeps track of current vehicle locations")
            Container(fleetService, "Fleet Service", "Service", "Receives updates from vehicles")
            }

        Container_Boundary(c3, "Vehicle Communication Subsystem") {
            ContainerQueue(messageBroker, "Message Broker")
            Container(eVehicle, "e-scooter/bike")
        }
    }


    Rel(user, mobile, "Uses", "HTTPS")
    Rel(mobile, webserver, "Makes API calls to", "HTTPS/JSON")
    Rel(webserver, paymentService, "Validates payment methods", "Internal API")
    Rel(webserver, locationService, "Fetches vehicle location", "Internal API")
    Rel(webserver, bookingService, "Books a vehicle", "Internal API")
    Rel(bookingService, locationService, "Notifies that a vehicle is booked", "Event")
    Rel(fleetService, messageBroker, "Published GPS events, battery status events")
    Rel(eVehicle, fleetService, "Sends current position and remaining charge", "External API")
    Rel(fleetService, messageBroker, "Updates with vehicle position and charge", "Event")
    Rel(messageBroker, locationService, "Updates with vehicle position", "Event")

