C4Container
    title Container Diagram for e-scooter and e-bike rental
    UpdateLayoutConfig($c4ShapeInRow="2", $c4BoundaryInRow="1")
    Enterprise_Boundary(b1, "MobiCorp Feedback System") {
        Person(user, "User", "A MobiCorp user")
        Container(mobile, "Mobile App", "iOS/Android", "Allows customer to enter feedback", "Via API Gateway")
        Container(userService, "User Service", "Service", "Tracks app usage and ride data")

        Container_Boundary(c1, "Feedback Analysis Subsystem") {
            Container(feedbackService, "Feedback Service", "Service", "Receives user feedback")
            Container(statisticsService, "Statistics Service", "Service", "Aggregates info about problematic locations")
            Container(feedbackAiAnalyzer, "Feedback AI analyzer", "Service", "Classifies feedback/extracts data")
        }

        Container_Boundary(c2, "Fleet Ops Subsystem") {
            Container(maintenanceService, "Maintenance Service", "Service", "Collects info about vehicles to fix")
        }
    }

    Rel(mobile, userService, "Sends app usage info", "Events")
    Rel(user, mobile, "Sends feedback", "Options/Free text")
    Rel(mobile, feedbackService, "Send feedback", "Via API Gateway")
    Rel(feedbackService, feedbackAiAnalyzer, "Send feedback for analysis", "Messaging")
    Rel(feedbackAiAnalyzer, statisticsService, "Send problematic locations", "Messaging")
    Rel(feedbackService, userService, "Gets ride info", "Internal API")
    Rel(feedbackAiAnalyzer, maintenanceService, "Describes issues with vehicles", "Messaging")

